import { TypedEventEmitter } from "@libp2p/interface";
import { messageHash } from "@waku/core";
import {
  type Callback,
  type IDecodedMessage,
  type IDecoder,
  type IEncoder,
  type IMessage,
  ISendOptions,
  type IWaku,
  ProtocolError,
  SDKProtocolResult
} from "@waku/interfaces";
import {
  type HistoryEntry,
  Message as SdsMessage,
  MessageChannel as SdsMessageChannel,
  MessageChannelEvent as SdsMessageChannelEvent,
  type MessageChannelOptions as SdsMessageChannelOptions
} from "@waku/sds";
import { Logger } from "@waku/utils";

import { RetryManager } from "./retry_manager.js";

const log = new Logger("sdk:e2e-reliability");

const DEFAULT_SYNC_MIN_INTERVAL_MS = 30 * 1000; // 30 seconds
const DEFAULT_RETRY_INTERVAL_MS = 60 * 1000; // 60 seconds
const DEFAULT_MAX_RETRY_ATTEMPTS = 10;

const IRRECOVERABLE_SENDING_ERRORS: ProtocolError[] = [
  ProtocolError.ENCODE_FAILED,
  ProtocolError.EMPTY_PAYLOAD,
  ProtocolError.SIZE_TOO_BIG,
  ProtocolError.RLN_PROOF_GENERATION,
  ProtocolError.TOPIC_DECODER_MISMATCH,
  ProtocolError.INVALID_DECODER_TOPICS
];

/**
 * Messages are uniquely identified by the payload generated by the encoder,
 * ie, pre-sds wrap, but post encryption.
 * The Message id is the hex of said payload's hash
 */
export type MessageId = string;

export enum MessageChannelEvent {
  /**
   * The message is being sent over the wire.
   *
   * This event may be emitted several times if the retry mechanism kicks in.
   */
  OutMessageSending = "channel:out:message-sending",
  /**
   * The message has been sent over the wire but has not been acknowledged by
   * any other party yet.
   *
   * We are now waiting for acknowledgements.
   *
   * This event may be emitted several times if the
   * several times if the retry mechanisms kicks in.
   */
  OutMessageSent = "channel:out:message-sent",
  /**
   * A received bloom filter seems to indicate that the messages was received
   * by another party.
   *
   * However, this is probabilistic. The retry mechanism will wait a bit longer
   * before trying to send the message again.
   */
  OutMessagePossiblyAcknowledged = "channel:out:message-possibly-acknowledged",
  /**
   * The message was fully acknowledged by other members of the channel
   */
  OutMessageAcknowledged = "channel:out:message-acknowledged",
  /**
   * The retry mechanism failed too many times, and the message is not considered
   * as sent.
   */
  OutMessageRetriesError = "channel:out:message-retries-error",
  /**
   * It was not possible to send the messages due to a non-recoverable error,
   * most likely an internal error for a developer to resolve.
   */
  OutMessageIrrecoverableError = "channel:out:message-irrecoverable-error",
  /**
   * A new message has been received.
   */
  InMessageReceived = "channel:in:message-received",
  /**
   * We are aware of a missing message but failed to retrieve it successfully.
   */
  InIrretrievableMessage = "channel:in:message-irretrievable"
}

export type MessageChannelEvents = {
  [MessageChannelEvent.OutMessageSending]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessageSent]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessagePossiblyAcknowledged]: CustomEvent<{
    messageId: MessageId;
    possibleAckCount: number;
  }>;
  [MessageChannelEvent.OutMessageAcknowledged]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessageRetriesError]: CustomEvent<MessageId>;
  // TODO probably T extends IDecodedMessage?
  [MessageChannelEvent.InMessageReceived]: CustomEvent<IDecodedMessage>;
  [MessageChannelEvent.InIrretrievableMessage]: CustomEvent<HistoryEntry>;
  [MessageChannelEvent.OutMessageIrrecoverableError]: CustomEvent<{
    messageId: MessageId;
    error: ProtocolError;
  }>;
};

export type MessageChannelOptions = SdsMessageChannelOptions & {
  /**
   * The minimum interval between 2 sync messages in the channel.
   *
   * Meaning, how frequently we want messages in the channel, noting that the
   * responsibility of sending a sync messages is shared between participants
   * of the channel.
   *
   * `0` means no sync messages will be sent.
   *
   * @default 30,000 (30 seconds) [[DEFAULT_SYNC_MIN_INTERVAL_MS]]
   */
  syncMinIntervalMs?: number;

  /**
   * How long to wait before re-sending a message that as not acknowledged.
   *
   * @default 60,000 (60 seconds) [[DEFAULT_RETRY_INTERVAL_MS]]
   */
  retryIntervalMs?: number;

  /**
   * How many times do we attempt resending messages that were not acknowledged.
   *
   * @default 10 [[DEFAULT_MAX_RETRY_ATTEMPTS]]
   */
  maxRetryAttempts?: number;
};

/**
 * Use events to track:
 * - if your outgoing messages are sent, acknowledged or error out
 * - for new incoming messages
 * @emits [[MessageChannelEvents]]
 *
 */
export class MessageChannel extends TypedEventEmitter<MessageChannelEvents> {
  private readonly _send: (
    encoder: IEncoder,
    message: IMessage,
    sendOptions?: ISendOptions
  ) => Promise<SDKProtocolResult>;

  private readonly _subscribe: <T extends IDecodedMessage>(
    decoders: IDecoder<T> | IDecoder<T>[],
    callback: Callback<T>
  ) => Promise<boolean>;

  private readonly syncMinIntervalMs: number;
  private syncTimeout: ReturnType<typeof setTimeout> | undefined;
  private readonly retryManager: RetryManager;

  private constructor(
    public node: IWaku,
    public messageChannel: SdsMessageChannel,
    private encoder: IEncoder,
    options?: MessageChannelOptions
  ) {
    super();
    if (node.lightPush) {
      this._send = node.lightPush.send.bind(node.lightPush);
    } else if (node.relay) {
      this._send = node.relay.send.bind(node.relay);
    } else {
      throw "No protocol available to send messages";
    }

    if (node.filter) {
      this._subscribe = node.filter.subscribe.bind(node.filter);
    } else if (node.relay) {
      // TODO: Why do relay and filter have different interfaces?
      //  this._subscribe = node.relay.subscribeWithUnsubscribe;
      throw "Not implemented";
    } else {
      throw "No protocol available to receive messages";
    }

    this.syncMinIntervalMs =
      options?.syncMinIntervalMs ?? DEFAULT_SYNC_MIN_INTERVAL_MS;

    const retryIntervalMs =
      options?.retryIntervalMs ?? DEFAULT_RETRY_INTERVAL_MS;
    const maxRetryAttempts =
      options?.maxRetryAttempts ?? DEFAULT_MAX_RETRY_ATTEMPTS;

    // TODO: there is a lot to improve. e.g. not point retry to send if node is offline.
    this.retryManager = new RetryManager(retryIntervalMs, maxRetryAttempts);

    this.setupEventListeners();
  }

  /**
   * Used to identify messages, pass the payload of a message you are
   * about to send to track the events for this message.
   * This is pre-sds wrapping
   * @param messagePayload
   */
  public static getMessageId(messagePayload: Uint8Array): string {
    return SdsMessageChannel.getMessageId(messagePayload);
  }

  /**
   * Create a new message channels. Message channels enables end-to-end
   * reliability by ensuring that all messages in the channel are received
   * by other users, and retrieved by this local node.
   *
   * emits events about outgoing messages, see [[`MessageChannel`]] docs.
   *
   * Note that all participants in a message channels need to get the messages
   * from the channel. Meaning:
   * - all participants must be able to decrypt the messages
   * - all participants must be subscribing to content topic(s) where the messages are sent
   *
   * @param node The waku node to use to send and receive messages
   * @param channelId An id for the channel, all participants of the channel should use the same id
   * @param encoder A channel operates within a singular encryption layer, hence the same encoder is needed for all messages
   * @param options
   */
  public static create(
    node: IWaku,
    channelId: string,
    encoder: IEncoder,
    options?: MessageChannelOptions
  ): MessageChannel {
    const sdsMessageChannel = new SdsMessageChannel(channelId, options);
    const messageChannel = new MessageChannel(
      node,
      sdsMessageChannel,
      encoder,
      options
    );

    messageChannel.start();
    return messageChannel;
  }

  /**
   * Sends a message in the channel, will attempt to re-send if not acknowledged
   * by other participants.
   *
   * @param messagePayload
   */
  // TODO: check we are listening before sending other SDS cannot work.
  public async send(messagePayload: Uint8Array): Promise<void> {
    const send = this.send_.bind(this, messagePayload);
    const messageId = MessageChannel.getMessageId(messagePayload);
    this.retryManager.startRetries(messageId, send);

    return send();
  }

  private async send_(messagePayload: Uint8Array): Promise<void> {
    await this.messageChannel.pushOutgoingMessage(
      messagePayload,
      async (
        sdsMessage: SdsMessage
      ): Promise<{ success: boolean; retrievalHint?: Uint8Array }> => {
        // Callback is called once message has added to the SDS outgoing queue
        // We start by trying to send the message now.

        // `payload` wrapped in SDS
        const sdsPayload = sdsMessage.encode();

        const wakuMessage = {
          payload: sdsPayload
        };

        // TODO: should the encoder give me the message hash?
        // Encoding now to fail early, used later to get message hash
        const protoMessage = await this.encoder.toProtoObj(wakuMessage);
        if (!protoMessage) {
          return { success: false };
        }

        const messageId = MessageChannel.getMessageId(messagePayload);
        this.safeSendEvent(MessageChannelEvent.OutMessageSending, {
          detail: messageId
        });

        const sendRes = await this._send(this.encoder, wakuMessage);

        // If it's a recoverable failure, we will try again to send later
        // If not, then we should error to the user now
        for (const { error } of sendRes.failures) {
          if (IRRECOVERABLE_SENDING_ERRORS.includes(error)) {
            // Not recoverable, best to return it
            log.error("Irrecoverable error, cannot send message: ", error);
            this.safeSendEvent(
              MessageChannelEvent.OutMessageIrrecoverableError,
              {
                detail: {
                  messageId,
                  error
                }
              }
            );
            return { success: false };
          }
        }

        const retrievalHint = messageHash(
          this.encoder.pubsubTopic,
          protoMessage
        );
        return {
          success: true,
          retrievalHint
        };
      }
    );

    // Process outgoing messages straight away
    // TODO: review and optimize
    await this.messageChannel.processTasks();
  }

  /**
   * Subscribe to a content topic to receive messages. Received messages will
   * be used to determined if a previous message was sent, and whether
   * messages are missed.
   *
   * emits events about incoming messages, see [[`MessageChannel`]] docs.
   *
   * @param decoders[]
   */
  public async subscribe<T extends IDecodedMessage>(
    decoders: IDecoder<T> | IDecoder<T>[]
  ): Promise<boolean> {
    return this._subscribe(decoders, async (msg: T): Promise<void> => {
      // New message arrives, we need to unwrap it first
      const sdsMessage = SdsMessage.decode(msg.payload);

      // SDS Message decoded, let's pass it to the channel so we can learn about
      // missing messages or the status of previous outgoing messages
      this.messageChannel.pushIncomingMessage(sdsMessage);

      if (sdsMessage.content && sdsMessage.content.length > 0) {
        // Now, process the message with callback

        // Overrides msg.payload with unwrapped payload
        // `payload` is just here to be discarded
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { payload, ...allButPayload } = msg;
        const unwrappedMessage = Object.assign(allButPayload, {
          payload: sdsMessage.content
        });

        this.safeSendEvent(MessageChannelEvent.InMessageReceived, {
          detail: unwrappedMessage as unknown as T
        });
      }

      // Do a process straight away
      // TODO: review and optimize
      await this.messageChannel.processTasks();
    });
  }

  private start(): void {
    this.restartSync();
  }

  private restartSync(): void {
    if (this.syncTimeout) {
      clearTimeout(this.syncTimeout);
    }
    if (this.syncMinIntervalMs) {
      // wait up to the interval threshold
      // random wait so that not all participants send a message at the same time
      // Also holding by 100ms as there is network propagation and a surge
      // Of sync messages would not be helpful to anyone

      // random is between 0.1 and 1
      const random = this.random() * 0.9 + 0.1;
      const timeoutMs = random * this.syncMinIntervalMs;

      this.syncTimeout = setTimeout(() => {
        void this.sendSyncMessage();
        // Always restart a sync, no matter whether the message was sent.
        void this.restartSync();
      }, timeoutMs);
    }
  }

  // Used to enable overriding when testing
  private random(): number {
    return Math.random();
  }

  private safeSendEvent<T extends MessageChannelEvent>(
    event: T,
    eventInit?: CustomEventInit
  ): void {
    try {
      this.dispatchEvent(new CustomEvent(event, eventInit));
    } catch (error) {
      log.error(`Failed to dispatch event ${event}:`, error);
    }
  }

  public async sendSyncMessage(): Promise<void> {
    log.info("Sending Sync Message");
    await this.messageChannel.pushOutgoingSyncMessage(
      async (sdsMessage: SdsMessage): Promise<boolean> => {
        // Callback is called once message has added to the SDS outgoing queue
        // We start by trying to send the message now.

        // `payload` wrapped in SDS
        const sdsPayload = sdsMessage.encode();

        const wakuMessage = {
          payload: sdsPayload
        };

        // TODO: should the encoder give me the message hash?
        // Encoding now to fail early, used later to get message hash
        const protoMessage = await this.encoder.toProtoObj(wakuMessage);
        if (!protoMessage) {
          return false;
        }

        const sendRes = await this._send(this.encoder, wakuMessage);
        if (sendRes.failures.length > 0) {
          log.error("Error sending sync message: ", sendRes);
          return false;
        }

        return true;
      }
    );

    // Process outgoing messages straight away
    // TODO: review and optimize
    await this.messageChannel.processTasks();
  }

  private setupEventListeners(): void {
    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.OutMessageSent,
      (event) => {
        if (event.detail.content) {
          const messageId = MessageChannel.getMessageId(event.detail.content);
          this.safeSendEvent(MessageChannelEvent.OutMessageSent, {
            detail: messageId
          });
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.OutMessageAcknowledged,
      (event) => {
        if (event.detail) {
          this.safeSendEvent(MessageChannelEvent.OutMessageAcknowledged, {
            detail: event.detail
          });

          // Stopping retries
          this.retryManager.stopRetries(event.detail);
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.OutMessagePossiblyAcknowledged,
      (event) => {
        if (event.detail) {
          this.safeSendEvent(
            MessageChannelEvent.OutMessagePossiblyAcknowledged,
            {
              detail: {
                messageId: event.detail.messageId,
                possibleAckCount: event.detail.count
              }
            }
          );
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.InSyncReceived,
      (_event) => {
        // restart the timeout when a sync message has been received
        this.restartSync();
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.InMessageReceived,
      (event) => {
        // restart the timeout when a non-ephemeral message has been received
        if (!event.detail.lamportTimestamp) {
          this.restartSync();
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.OutMessageSent,
      (event) => {
        // restart the timeout when a non-ephemeral message has been sent
        if (!event.detail.lamportTimestamp) {
          this.restartSync();
        }
      }
    );
  }
}
