import { TypedEventEmitter } from "@libp2p/interface";
import { messageHash } from "@waku/core";
import {
  type Callback,
  type IDecodedMessage,
  type IDecoder,
  type IEncoder,
  type IMessage,
  ISendOptions,
  type IWaku,
  ProtocolError,
  SDKProtocolResult
} from "@waku/interfaces";
import {
  HistoryEntry,
  type MessageChannelOptions,
  Message as SdsMessage,
  MessageChannel as SdsMessageChannel,
  MessageChannelEvent as SdsMessageChannelEvent
} from "@waku/sds";
import { Logger } from "@waku/utils";

const log = new Logger("sdk:e2e-reliability");

const IRRECOVERABLE_SENDING_ERRORS: ProtocolError[] = [
  ProtocolError.ENCODE_FAILED,
  ProtocolError.EMPTY_PAYLOAD,
  ProtocolError.SIZE_TOO_BIG,
  ProtocolError.RLN_PROOF_GENERATION,
  ProtocolError.TOPIC_DECODER_MISMATCH,
  ProtocolError.INVALID_DECODER_TOPICS
];

/**
 * Messages are uniquely identified by the payload generated by the encoder,
 * ie, pre-sds wrap, but post encryption.
 * The Message id is the hex of said payload's hash
 */
export type MessageId = string;

export enum MessageChannelEvent {
  /**
   * The message is being sent over the wire.
   *
   * This event may be emitted several times if the retry mechanism kicks in.
   */
  OutMessageSending = "channel:out:message:sending",
  /**
   * The message has been sent over the wire but has not been acknowledged by
   * any other party yet.
   *
   * We are now waiting for acknowledgements.
   *
   * This event may be emitted several times if the
   * several times if the retry mechanisms kicks in.
   */
  OutMessageSent = "channel:out:message:sent",
  /**
   * A received bloom filter seems to indicate that the messages was received
   * by another party.
   *
   * However, this is probabilistic. The retry mechanism will wait a bit longer
   * before trying to send the message again.
   */
  OutMessagePossiblyAcknowledged = "channel:out:message:possibly-acknowledged",
  /**
   * The message was fully acknowledged by other members of the channel
   */
  OutMessageAcknowledged = "channel:out:message:acknowledged",
  /**
   * The retry mechanism failed too many times, and the message is not considered
   * as sent.
   */
  OutMessageFailed = "channel:out:message:failed",
  /**
   * A new message has been received.
   */
  InMessageReceived = "channel:in:message:received",
  /**
   * We are aware of a missing message but failed to retrieve it successfully.
   */
  InIrretrievableMessage = "channel:in:message:irretrievable"
}

export type MessageChannelEvents = {
  [MessageChannelEvent.OutMessageSending]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessageSent]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessagePossiblyAcknowledged]: CustomEvent<{
    messageId: MessageId;
    possibleAckCount: number;
  }>;
  [MessageChannelEvent.OutMessageAcknowledged]: CustomEvent<MessageId>;
  [MessageChannelEvent.OutMessageFailed]: CustomEvent<MessageId>;
  // TODO probably T extends IDecodedMessage?
  [MessageChannelEvent.InMessageReceived]: CustomEvent<IDecodedMessage>;
  [MessageChannelEvent.InIrretrievableMessage]: CustomEvent<HistoryEntry>;
};

/**
 * Use events to track:
 * - if your outgoing messages are sent, acknowledged or error out
 * - for new incoming messages
 * @emits [[MessageChannelEvents]]
 */
export class MessageChannel extends TypedEventEmitter<MessageChannelEvents> {
  private readonly _send: (
    encoder: IEncoder,
    message: IMessage,
    sendOptions?: ISendOptions
  ) => Promise<SDKProtocolResult>;

  private readonly _subscribe: <T extends IDecodedMessage>(
    decoders: IDecoder<T> | IDecoder<T>[],
    callback: Callback<T>
  ) => Promise<boolean>;

  private constructor(
    public node: IWaku,
    public messageChannel: SdsMessageChannel
  ) {
    super();
    if (node.lightPush) {
      this._send = node.lightPush.send.bind(node.lightPush);
    } else if (node.relay) {
      this._send = node.relay.send.bind(node.relay);
    } else {
      throw "No protocol available to send messages";
    }

    if (node.filter) {
      this._subscribe = node.filter.subscribe.bind(node.filter);
    } else if (node.relay) {
      // TODO: Why do relay and filter have different interfaces?
      //  this._subscribe = node.relay.subscribeWithUnsubscribe;
      throw "Not implemented";
    } else {
      throw "No protocol available to receive messages";
    }

    this.setupEventListeners();
  }

  /**
   * Used to identify messages, pass the payload of a message you are
   * about to send to track the events for this message.
   * @param payload
   */
  public static getMessageId(payload: Uint8Array): string {
    return SdsMessageChannel.getMessageId(payload);
  }

  /**
   * Create a new message channels. Message channels enables end-to-end
   * reliability by ensuring that all messages in the channel are received
   * by other users, and retrieved by this local node.
   *
   * emits events about outgoing messages, see [[`MessageChannel`]] docs.
   *
   * Note that all participants in a message channels need to get the messages
   * from the channel. Meaning:
   * - all participants must be able to decrypt the messages
   * - all participants must be subscribing to content topic(s) where the messages are sent
   *
   * @param node
   * @param channelId
   * @param channelOptions
   */
  public static create(
    node: IWaku,
    channelId: string,
    channelOptions?: MessageChannelOptions
  ): MessageChannel {
    const sdsMessageChannel = new SdsMessageChannel(channelId, channelOptions);
    return new MessageChannel(node, sdsMessageChannel);
  }

  /**
   * Sends a message in the channel, will attempt to re-send if not acknowledged
   * by other participants.
   *
   * @param encoder
   * @param message
   */
  public async send(encoder: IEncoder, message: IMessage): Promise<void> {
    await this.messageChannel.pushOutgoingMessage(
      message.payload,
      async (
        sdsMessage: SdsMessage
      ): Promise<{ success: boolean; retrievalHint?: Uint8Array }> => {
        // Callback is called once message has added to the SDS outgoing queue
        // We start by trying to send the message now.

        // `payload` wrapped in SDS
        const sdsPayload = sdsMessage.encode();

        const wakuMessage = {
          payload: sdsPayload,
          timestamp: message.timestamp,
          rateLimitProof: message.rateLimitProof
        };

        // TODO: Shouldn't the encoder give me this easily?
        const protoMessage = await encoder.toProtoObj(wakuMessage);
        if (!protoMessage) {
          return { success: false };
        }

        const messageId = MessageChannel.getMessageId(message.payload);
        this.safeSendEvent(MessageChannelEvent.OutMessageSending, {
          detail: messageId
        });

        const sendRes = await this._send(encoder, wakuMessage);

        // If it's a recoverable failure, we will try again to send letter
        // If not, then we should error to the user now
        for (const { error } of sendRes.failures) {
          if (IRRECOVERABLE_SENDING_ERRORS.includes(error)) {
            // Not recoverable, best to return it
            // TODO: Should we emit?
            log.error("Irrecoverable error, cannot send message: ", error);
            return { success: false };
          }
        }

        const retrievalHint = messageHash(encoder.pubsubTopic, protoMessage);
        return {
          success: true,
          retrievalHint
        };
      }
    );

    // Process outgoing messages straight away
    // TODO: review and optimize
    await this.messageChannel.processTasks();
  }

  /**
   * Subscribe to a content topic to receive messages. Received messages will
   * be used to determined if a previous message was sent, and whether
   * messages are missed.
   *
   * emits events about incoming messages, see [[`MessageChannel`]] docs.
   *
   * @param decoders[]
   */
  public async subscribe<T extends IDecodedMessage>(
    decoders: IDecoder<T> | IDecoder<T>[]
  ): Promise<boolean> {
    return this._subscribe(decoders, async (msg: T): Promise<void> => {
      // New message arrives, we need to unwrap it first
      const sdsMessage = SdsMessage.decode(msg.payload);

      // SDS Message decoded, let's pass it to the channel so we can learn about
      // missing messages or the status of previous outgoing messages
      this.messageChannel.pushIncomingMessage(sdsMessage);

      if (sdsMessage.content) {
        // Now, process the message with callback

        // Overrides msg.payload with unwrapped payload
        // `payload` is just here to be discarded
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { payload, ...allButPayload } = msg;
        const unwrappedMessage = Object.assign(allButPayload, {
          payload: sdsMessage.content
        });

        this.safeSendEvent(MessageChannelEvent.InMessageReceived, {
          detail: unwrappedMessage as unknown as T
        });
      }

      // Do a process straight away
      // TODO: review and optimize
      await this.messageChannel.processTasks();
    });
  }

  private safeSendEvent<T extends MessageChannelEvent>(
    event: T,
    eventInit?: CustomEventInit
  ): void {
    try {
      this.dispatchEvent(new CustomEvent(event, eventInit));
    } catch (error) {
      log.error(`Failed to dispatch event ${event}:`, error);
    }
  }

  private setupEventListeners(): void {
    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.MessageSent,
      (event) => {
        if (event.detail.content) {
          const messageId = MessageChannel.getMessageId(event.detail.content);
          this.safeSendEvent(MessageChannelEvent.OutMessageSent, {
            detail: messageId
          });
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.MessageAcknowledged,
      (event) => {
        if (event.detail) {
          this.safeSendEvent(MessageChannelEvent.OutMessageAcknowledged, {
            detail: event.detail
          });
        }
      }
    );

    this.messageChannel.addEventListener(
      SdsMessageChannelEvent.MessagePossiblyAcknowledged,
      (event) => {
        if (event.detail) {
          this.safeSendEvent(
            MessageChannelEvent.OutMessagePossiblyAcknowledged,
            {
              detail: {
                messageId: event.detail.messageId,
                possibleAckCount: event.detail.count
              }
            }
          );
        }
      }
    );
  }
}
