export const DEFAULT_KEEP_ALIVE = 10_000;
export const DEFAULT_LIGHT_PUSH_FILTER_CHECK = false;
export const DEFAULT_LIGHT_PUSH_FILTER_CHECK_INTERVAL = 10_000;

export const DEFAULT_SUBSCRIBE_OPTIONS = {
  keepAlive: DEFAULT_KEEP_ALIVE,
  enableLightPushFilterCheck: DEFAULT_LIGHT_PUSH_FILTER_CHECK
};
