name: npm i

runs:
  using: "composite"
  steps:
    - if: ${{ github.ref == 'refs/heads/master' || github.head_ref == 'release-please--branches--master' }}
      run: npm i
      shell: bash
    - if: ${{ github.ref != 'refs/heads/master' && github.head_ref != 'release-please--branches--master' }}
      uses: bahmutov/npm-install@v1
