name: npm i

runs:
  using: "composite"
  steps:
    - run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
    - run: npm i
      shell: bash
      if: ${{ contains('
        refs/heads/master
        refs/heads/release-please--branches--master
        ', github.ref) }}
    - uses: bahmutov/npm-install@v1
      if: ${{ contains('
        refs/heads/master
        refs/heads/release-please--branches--master
        ', github.ref) == false }}
