pipeline {
  agent { label 'linux' }

  options {
    disableConcurrentBuilds()
    disableRestartFromStage()
    /* manage how many builds we keep */
    buildDiscarder(logRotator(
      numToKeepStr: '20',
      daysToKeepStr: '30',
    ))
  }

  environment {
    GIT_AUTHOR_NAME = 'status-im-auto'
    GIT_AUTHOR_EMAIL = 'auto@status.im'
    PUPPETEER_SKIP_DOWNLOAD = 'true'
    NO_COLOR = 'true'
  }

  stages {
    stage('Deps') {
      steps {
        sh 'npm install'
      }
    }

    stage('Packages') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run doc'
      }
    }

    stage('Publish') {
      when { expression { GIT_BRANCH.endsWith('master') } }
      steps {
        sshagent(credentials: ['status-im-auto-ssh']) {
          sh 'npm run deploy'
        }
      }
    }
  }
  post {
    always { cleanWs() }
  }
}
