on:
    workflow_dispatch:

env:
  NODE_JS: "24"

permissions:
  id-token: write  # Required for npmjs' OIDC
  contents: read

jobs:
    pre-release:
        name: pre-release
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
          - uses: actions/checkout@v4
            with:
              repository: waku-org/js-waku

          - uses: actions/setup-node@v4
            with:
              node-version: ${{ env.NODE_JS }}
              registry-url: "https://registry.npmjs.org"

          - run: npm install

          - run: npm run build

          - run: npm run publish -- --tag next
